version: "3"
services:
        wordpress:
                image: wordpress:5.7
                ports:
                        - 80:3306 # PORT??
                environment:
                        - WORDPRESS_DB_HOST=BDP10
                        - WORDPRESS_DB_USER=UsernameP10
                        - WORDPRESS_DB_PASSWORD=PasswordP10
                        - WORDPRESS_DB_NAME=wrdprssP10
                networks:
                        - p10_net
                volumes:
                        - /data/wp:/var/www/html
        db:
                image: mysql:5.7
                environment:
                        - MYSQL_ROOT_PASSWORD=root
                        - MYSQL_DATABASE=wrdprss
                        - MYSQL_HOST=BDP10
                        - MYSQL_USER=UsernameP10
                        - MYSQL_PASSWORD=PasswordP10
                networks:
                        - p10_net
                volumes:
                        - /data/bd:/var/lib/mysql ##### ???? partie Volume à dégager?
####### 
#volumes:
networks:
        p10_net: 
