version: "3"
services:
        wordpress:
                image: wordpress
                ports:
                        - 80:80 # PORT??
                environment:
                        - WORDPRESS_DB_HOST=BDP10
                        - WORDPRESS_DB_USER=UsernameP10
                        - WORDPRESS_DB_PASSWORD=PasswordP10
                        - WORDPRESS_DB_NAME=wrdprssP10
                volumes:
                        - wp_data:/var/www/html


        wordpress-cli:
                depends_on:
                        - wordpress
                image: wordpress:cli
                volumes:
                        - wp_data:/var/www/html



#                volumes:
#                        - efsaws:/var/www/html
#
#        BDP10: 
#                image: mysql:5.7
#                environment:
#        ⦙       ⦙       - MYSQL_ROOT_PASSWORD=root
#        ⦙       ⦙       - MYSQL_DATABASE=wrdprss
#        ⦙       ⦙       - MYSQL_HOST=BDP10
#        ⦙       ⦙       - MYSQL_USER=UsernameP10
#        ⦙       ⦙       - MYSQL_PASSWORD=PasswordP10
#
#
#volumes:
#         efsaws:
#                driver_opts:
#                        type: "nfs"
#                        device: ":/docker/efsaws"
#                        o: "addr=MPIP,nolock,soft,rw"
#
# MAPPING SUR EFS / VOLUMES


