version: "3"
services:
        wordpress:
                image: wordpress:5.7
                ports:
                        - 80:3306 # PORT??
                environment:
                        - WORDPRESS_DB_HOST=BDP10
                        - WORDPRESS_DB_USER=UsernameP10
                        - WORDPRESS_DB_PASSWORD=PasswordP10
                        - WORDPRESS_DB_NAME=wrdprssP10
