version: "3"
services:
        wordpress:
                image: wordpress:latest
                ports:
                        - 80:80 # PORT??
                environment:
                        - WORDPRESS_DB_HOST=BDP10
                        - WORDPRESS_DB_USER=UsernameP10
                        - WORDPRESS_DB_PASSWORD=PasswordP10
                        - WORDPRESS_DB_NAME=wrdprssP10
                volumes:
                        - /wp_data:/var/www/html


        wordpress-cli:
                depends_on:
                        - wordpress
                image: wordpress:cli
                environment:
                        - WORDPRESS_DB_HOST=BDP10
                        - WORDPRESS_DB_USER=UsernameP10
                        - WORDPRESS_DB_PASSWORD=PasswordP10
                        - WORDPRESS_DB_NAME=wrdprssP10
                volumes:
                        - /wp_data:/var/www/html
                user: xfs ### ??????? UID 33?????
                command: >
                        /bin/bash -c '
                        while [ ! -f wp-config.php ]; do
                        sleep 5;
                        date;
                        if [ -f wp-config.php ]; then
                        wp core install 
                        --path="/var/www/html" 
                        --url="WPURLDNS"
                        --title="Site Web pour P10"
                        --admin_user="wpuser"
                        --admin_password="wppassword"
                        --admin_email="wpemail";
                        echo "WP bien installé";
                        wp core version; fi; done;
                        wp plugin install amazon-web-services;
                        wp plugin activate amazon-web-services;
                        '
# ACTIVATE à la FIN!!!
#volumes:
#        wp_data:
#                driver_opts:
#                        type: "nfs4"
#                        device: ":/docker/wp_data"
#                        o: "addr=MTRIP,nolock,soft,rw"
#
#
#                volumes:
#                        - efsaws:/var/www/html
#
#        BDP10: 
#                image: mysql:5.7
#                environment:
#        ⦙       ⦙       - MYSQL_ROOT_PASSWORD=root
#        ⦙       ⦙       - MYSQL_DATABASE=wrdprss
#        ⦙       ⦙       - MYSQL_HOST=BDP10
#        ⦙       ⦙       - MYSQL_USER=UsernameP10
#        ⦙       ⦙       - MYSQL_PASSWORD=PasswordP10
#
#
#volumes:
#         efsaws:
#                driver_opts:
#                        type: "nfs"
#                        device: ":/docker/efsaws"
#                        o: "addr=MPIP,nolock,soft,rw"
#
# MAPPING SUR EFS / VOLUMES


