version: "3.8"
services:
        wordpress:
                build: /p10
                ports:
                        - 80:80 # PORT??
                environment:
                        - WORDPRESS_DB_HOST=BDP10
                        - WORDPRESS_DB_USER=UsernameP10
                        - WORDPRESS_DB_PASSWORD=PasswordP10
                        - WORDPRESS_DB_NAME=wrdprssP10
                volumes:
                        - /wp_data:/var/www/html

